
title: Kyle Ng Yee Han
theme: jekyll-theme-minimal
date: '2024-03-14'

<img src="https://cdn8.openculture.com/2021/01/20101921/solvay-bw.jpeg" alt="1927 Solvay Conference" style="border-radius: 50%; width: 200px; height: 200px; object-fit: cover;">
